#!/bin/bash
#
# ~/.dwmConfig/dwm-statusbar
#
# Colour codes from dwm/config.h

colour_red="\x05" #red
colour_blue="\x06" #blue
colour_green="\x07" #green
colour_dgrey="\x08" #dark grey
colour_lgrey="\x09" #light grey
colour_orange="\x0A" #orange
colour_ping="\x0B" #pink
colour_white="\x0D" #white


# Icon glyphs from font xbmicons.pcf
glyph_msc="\uE00E"
glyph_cpu="\uE00F"
glyph_mem="\uE010"
glyph_dl="\uE011"
glyph_ul="\uE012"
glyph_com="\uE013"
glyph_eml="\uE014"
glyph_vol="\uE015"
glyph_tim="\uE016"
glyph_tor="\uE017"
sep_solid="\uE01A"
sep_line="\uE01B"
sep_bar="\uE020"

print_song_info() {
  song_info="$(ncmpcpp --now-playing '{{{{%a - }%t}}|{%f}}' | head -c 75)"
  if [[ ! $song_info ]]; then
    song_info="Off"
  fi
  echo -ne "${colour_orange} ${glyph_msc} ${colour_dgrey}${song_info} "
}

print_mem_used() {
  mem_used="$(free -m | awk 'NR==2 {print $3}')"
  echo -ne "${sep_bar} ${glyph_mem} ${colour_dgrey}${mem_used}M "
}

print_volume() {
  volume="$(amixer get Master | tail -n1 | sed -r 's/.*\[(.*)%\].*/\1/')"
  echo -ne "${colour_orange} ${glyph_vol} ${colour_dgrey}${volume}% "
}

print_datetime() {
  datetime="$(date "+%a %d %b ${sep_bar} %H:%M")"
  echo -ne "${colour_orange} ${glyph_tim} ${colour_dgrey}${datetime} "
}

# network (from: http://dzen.geekmode.org/dwiki/doku.php?id=dzen:network-meter)
# cpu (from: https://bbs.archlinux.org/viewtopic.php?pid=661641#p661641)
rx_old=$(cat /sys/class/net/wlp2s0/statistics/rx_bytes)
tx_old=$(cat /sys/class/net/wlp2s0/statistics/tx_bytes)

while true; do
  # get new cpu idle and total usage
  eval $(awk '/^cpu /{print "cpu_idle_now=" $5 "; cpu_total_now=" $2+$3+$4+$5 }' /proc/stat)
  cpu_interval=$((cpu_total_now-${cpu_total_old:-0}))
  # calculate cpu usage (%)
  let cpu_used="100 * ($cpu_interval - ($cpu_idle_now-${cpu_idle_old:-0})) / $cpu_interval"

  # get new rx/tx counts
  rx_now=$(cat /sys/class/net/wlp2s0/statistics/rx_bytes)
  tx_now=$(cat /sys/class/net/wlp2s0/statistics/tx_bytes)
  # calculate the rate (K) and total (M)
  let rx_rate=($rx_now-$rx_old)/1024
  let tx_rate=($tx_now-$tx_old)/1024
  let rx_total=$rx_now/1048576
  let tx_total=$tx_now/1048576

  # output vars
  print_cpu_used() {
    printf "%-10b" "${colour_orange} ${glyph_cpu} ${colour_dgrey}${cpu_used}% "
  }
  print_rx_rate() {
    printf "%-11b" "${colour_orange} ${glyph_dl} ${colour_dgrey}${rx_rate}K "
  }
  print_rx_total() { 
    printf  "${rx_total}M" 
  }
  print_tx_rate() {
    printf "%-15b" "${colour_orange}${sep_bar} ${colour_orange}${glyph_ul} ${colour_dgrey}${tx_rate}K"
  }
  print_tx_total() { 
	printf  "${tx_total}M"
  }
  # Pipe to status bar, not indented due to printing extra spaces/tabs
  xsetroot -name "$(print_song_info)\
$(print_cpu_used)$(print_mem_used)\
$(print_rx_rate)$(print_rx_total)$(print_tx_rate)$(print_tx_total)\
$(print_volume)\
$(print_datetime)"

  # reset old rates
  rx_old=$rx_now
  tx_old=$tx_now
  cpu_idle_old=$cpu_idle_now
  cpu_total_old=$cpu_total_now
  # loop stats every 1 second
  sleep 1
done
