#!/bin/bash
#
# ~.dwmConfig/dwm-start
#

$HOME/.dwmConfig/dwm-statusbar &

while true; do
    # Log stderror to a file
    dwm >  $HOME/.logs/dwm.log
    # No error logging
    #dwm >/dev/null 2>&1
done
